### ISSUE TITLE
P0: develop branch has 3 type errors — all PRs blocked

### ISSUE THREAD

**Issue by kokevidaurre** [agents-squads/squads-cli#480]
## Problem

The develop branch fails typecheck with 3 errors, blocking all 10 open PRs:

- src/cli.ts(759,43): Cannot find module ./commands/stats.js
- src/commands/daemon.ts(26,8): Cannot find module ../lib/outcomes.js
- src/commands/run.ts(2421,51): No value exists in scope for shorthand property provider

## Context

Likely introduced by d0d0ccf6 (hard-stop fix) or 7b53cb29 (main merge into develop), both from ~8h ago.
All 10 open PRs (469-479) target develop and all fail CI.

## Fix

1. Add missing stats.js module or remove the import from cli.ts
2. Add missing outcomes.js module or remove the import from daemon.ts  
3. Fix the provider shorthand in run.ts line 2421

## Impact

P0 — zero PRs can merge until this is fixed. Blocks O2 product recovery entirely.
